# model parameters
source_path: "/workspace/data/walnut_noisy"
model_path: ""
ply_path: ""
data_device: "cuda"
scale_min: 0.0005
scale_max: 0.5
eval: true

# optimization parameters
iterations: 30000
position_lr_init: 0.0002
position_lr_final: 0.00002
position_lr_max_steps: 30000
density_lr_init: 0.01
density_lr_final: 0.001
density_lr_max_steps: 30000
scaling_lr_init: 0.005
scaling_lr_final: 0.0005
scaling_lr_max_steps: 30000
rotation_lr_init: 0.001
rotation_lr_final: 0.0001
rotation_lr_max_steps: 30000

translation_lr_init: 0.0002
translation_lr_final: 0.00002
translation_lr_max_steps: 30000
quaternion_lr_init: 0.0002
quaternion_lr_final: 0.00002
quaternion_lr_max_steps: 30000
fovx_lr_init: 0.0
fovx_lr_final: 0.0
fovx_lr_max_steps: 30000
fovy_lr_init: 0.0
fovy_lr_final: 0.0
fovy_lr_max_steps: 30000

mask_lr: 0.0
lambda_dssim: 0.25
tv_vol_size: 32
density_min_threshold: 0.00001
densification_interval: 100
densify_from_iter: 500
densify_until_iter: 15000
densify_grad_threshold: 5.0e-5
densify_scale_threshold: 0.1
use_reset: false
use_gt_mask: false
use_xyz_grad: false
use_hessian: false
use_volume_mask: false
export_cam_params: true
debug_proj_images: false
erank_value: 2      # default: 2
mask_prune_iter: 1000
max_screen_size: null
max_scale: null
max_num_gaussians: 500000

# pipeline parameters
compute_cov3D_python: false
debug: false